# install with ansible-galaxy collection install -r ansible/requirements.yml

collections:
- name: https://github.com/kubernetes-sigs/kubespray
  type: git
  version: master # use the appropriate tag or branch for the version you need